##############################################################
#               Krathalan's btm config/theme                 #
#         Homepage: https://github.com/krathalan/dots        #
#        Copyright (C) 2020 krathalan; License: GPLv3        #
##############################################################

[flags]
avg_cpu = true
temperature_type = "c"
rate = 1000
left_legend = true
current_usage = false
group_processes = false
case_sensitive = false
whole_word = false
regex = true
show_disabled_data = false
default_widget_type = "processes"
default_widget_count = 1

[colors]
# Based on World of Warcraft class colors
# And my alacritty config :)
table_header_color="#aaaaaa"
widget_title_color="#00ff96"
avg_cpu_color="#00ff96"
cpu_core_colors=["#fff569", "#66b3ff", "#b3a6d8", "#dd2241", "#5dcfee", "#ffffff", "#5f5f5f", "#00ff96"]
ram_color="#b3a6d8"
swap_color="#fff569"
rx_color="#66b3ff"
tx_color="#5f5f5f"
border_color="#5dcfee"
highlighted_border_color="#00ff96"
text_color="#ffffff"
graph_color="#aaaaaa"
selected_text_color="#000000"
selected_bg_color="#66b3ff"

[[row]]
    ratio=2
    [[row.child]]
      ratio=4
      type="cpu"
    [[row.child]]
      ratio=3
      [[row.child.child]]
        type="mem"
      [[row.child.child]]
        type="temp"
[[row]]
    ratio=1
    [[row.child]]
      type="network"
    [[row.child]]
      type="processes"
